id: PA0DB1B77
initial_creation_type: input
source_metadata:
  Title: The Gilgit Manuscript of the Sayanasanavastu and the Adhikaranavastu
  Editor: Raniero Gnoli
  Publisher: Istituto Italiano Per Il Medio Ed Estremo Oriente
  Place of Publication: Roma
  Year: '1978'
  अधिकरणवस्तु:
    Text Version: Devanagari
    Input Personnel: Milan Shakya
    Input Date: July, 2017
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T17:02:16.614018'
last_modified_at: '2022-03-08T17:02:16.614026'
